"""
Application entry point
Generated by RDT v2.0
"""
from src import create_app

app = create_app()

if __name__ == '__main__':
    app.run(
        host='0.0.0.0',
        port=5300,
        debug=False
    )